#!/usr/bin/env node
/**
 * Polish-9.5: build-time bundling of prompt .md files into a TS module.
 *
 * Background: Polish-6 loaded prompts via fs.readFileSync at runtime,
 * which relied on Vercel's outputFileTracingIncludes to copy .md files
 * into the serverless function bundle. That tracing config didn't
 * actually land the files in production, crashing every Kling/Sora/
 * Nano-Banana run with "Could not locate prompts directory".
 *
 * Fix: at build time, read every prompts/**\/*.md and emit a TS module
 * that exports the content as a string map. prompt-loader.ts imports
 * from this generated module instead of doing fs.readFileSync — the
 * prompt text ships inside the JS bundle, no file-tracing needed.
 *
 * The .md sources stay the source of truth. This script writes them
 * verbatim into a template literal (backticks + ${} escaped).
 *
 * Idempotent: safe to re-run. Output goes to src/generated/.
 */

import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROMPTS_DIR = join(__dirname, '..', 'src', 'prompts');
const OUTPUT_DIR = join(__dirname, '..', 'src', 'generated');
const OUTPUT_FILE = join(OUTPUT_DIR, 'prompts-bundle.ts');

function walk(dir) {
  const out = [];
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...walk(full));
    } else if (entry.endsWith('.md')) {
      out.push(full);
    }
  }
  return out;
}

/**
 * Escape a string so it's safe inside a JS template literal.
 * - Escape backslashes first.
 * - Escape backticks (template literal delimiters).
 * - Escape ${ sequences (template literal interpolation start).
 *
 * No other escaping — newlines, quotes, and other characters pass
 * through verbatim. This preserves byte-for-byte prompt fidelity.
 */
function escapeForTemplateLiteral(s) {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function main() {
  if (!existsSync(PROMPTS_DIR)) {
    // No prompts dir → emit an empty bundle so downstream TS compiles.
    // Happens in monorepo consumers that don't ship the prompts subtree.
    console.log('[build-prompts] no prompts/ dir — emitting empty bundle');
    writeEmpty();
    return;
  }

  const files = walk(PROMPTS_DIR).sort();
  const entries = files.map((abs) => {
    const rel = relative(PROMPTS_DIR, abs).replace(/\\/g, '/').replace(/\.md$/, '');
    const content = readFileSync(abs, 'utf-8');
    return { key: rel, content };
  });

  const body = entries
    .map((e) => `  ${JSON.stringify(e.key)}: \`${escapeForTemplateLiteral(e.content)}\``)
    .join(',\n');

  const out =
    '// AUTO-GENERATED by scripts/build-prompts.mjs — do not edit by hand.\n' +
    '// Regenerate with: pnpm --filter @mbb/ai-providers build:prompts\n' +
    '/* eslint-disable */\n\n' +
    'export const PROMPTS: Readonly<Record<string, string>> = {\n' +
    body +
    ',\n} as const;\n';

  mkdirSync(OUTPUT_DIR, { recursive: true });
  writeFileSync(OUTPUT_FILE, out, 'utf-8');
  console.log(`[build-prompts] wrote ${entries.length} prompts → ${OUTPUT_FILE}`);
}

function writeEmpty() {
  mkdirSync(OUTPUT_DIR, { recursive: true });
  writeFileSync(
    OUTPUT_FILE,
    '// AUTO-GENERATED by scripts/build-prompts.mjs (empty — no prompts/ dir found)\n' +
      '/* eslint-disable */\n\n' +
      'export const PROMPTS: Readonly<Record<string, string>> = {} as const;\n',
    'utf-8',
  );
}

try {
  main();
} catch (err) {
  // Never crash install — emit empty bundle as a fallback so TS still compiles.
  console.error('[build-prompts] failed:', err);
  try {
    writeEmpty();
  } catch {
    // ignore
  }
  process.exit(0);
}
