import { sql } from 'drizzle-orm';
import { boolean, jsonb, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { aiProviderEnum, connectionMethodEnum, connectionStatusEnum } from './enums';
import { users } from './users';

/**
 * Meta Business Manager connection. One per user (we may relax this later).
 *
 * Tokens are stored encrypted via pgcrypto. The *_encrypted columns below
 * hold ciphertext. Plaintext NEVER leaves the decrypt helper in
 * @mbb/db/safety/encryption. See supabase/migrations/0002_vault.sql.
 */
export const metaConnections = pgTable('meta_connections', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),

  fbUserId: text('fb_user_id'),
  businessManagerId: text('business_manager_id'),
  // Array of ad account ids the user authorized for bot management.
  adAccountIds: text('ad_account_ids')
    .array()
    .notNull()
    .default(sql`'{}'::text[]`),

  // Encrypted via pgcrypto + Supabase Vault key.
  accessTokenEncrypted: text('access_token_encrypted'),
  refreshTokenEncrypted: text('refresh_token_encrypted'),
  tokenExpiresAt: timestamp('token_expires_at', { withTimezone: true }),

  connectionMethod: connectionMethodEnum('connection_method').notNull().default('byok'),
  status: connectionStatusEnum('status').notNull().default('pending'),

  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
  lastVerifiedAt: timestamp('last_verified_at', { withTimezone: true }),

  // Soft delete.
  deletedAt: timestamp('deleted_at', { withTimezone: true }),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const telegramConnections = pgTable('telegram_connections', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),

  // Telegram chat id. Numeric in TG, stored as text for safety.
  tgChatId: text('tg_chat_id'),
  // One-time link code generated by web, redeemed by `/start <code>` in TG.
  linkCode: text('link_code').unique(),
  linkedAt: timestamp('linked_at', { withTimezone: true }),

  status: connectionStatusEnum('status').notNull().default('pending'),

  metadata: jsonb('metadata').$type<{ tgUsername?: string }>(),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const aiProviderConnections = pgTable('ai_provider_connections', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),

  provider: aiProviderEnum('provider').notNull(),

  // Encrypted via pgcrypto + Supabase Vault key.
  apiKeyEncrypted: text('api_key_encrypted').notNull(),
  apiKeyVerifiedAt: timestamp('api_key_verified_at', { withTimezone: true }),

  status: connectionStatusEnum('status').notNull().default('pending'),
  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),

  // Soft delete.
  deletedAt: timestamp('deleted_at', { withTimezone: true }),

  isPrimary: boolean('is_primary').notNull().default(false),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
