import { sql } from 'drizzle-orm';
import { boolean, integer, jsonb, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import {
  aiProviderEnum,
  connectionMethodEnum,
  connectionStatusEnum,
  providerTierEnum,
  toolProviderEnum,
} from './enums';
import { users } from './users';

/**
 * Meta Business Manager connection. One per user (we may relax this later).
 *
 * Tokens are stored encrypted via pgcrypto. The *_encrypted columns below
 * hold ciphertext. Plaintext NEVER leaves the decrypt helper in
 * @mbb/db/safety/encryption. See supabase/migrations/0002_vault.sql.
 */
export const metaConnections = pgTable('meta_connections', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),

  fbUserId: text('fb_user_id'),
  businessManagerId: text('business_manager_id'),
  // Array of ad account ids the user authorized for bot management.
  adAccountIds: text('ad_account_ids')
    .array()
    .notNull()
    .default(sql`'{}'::text[]`),

  // Encrypted via pgcrypto + Supabase Vault key.
  accessTokenEncrypted: text('access_token_encrypted'),
  refreshTokenEncrypted: text('refresh_token_encrypted'),
  tokenExpiresAt: timestamp('token_expires_at', { withTimezone: true }),

  connectionMethod: connectionMethodEnum('connection_method').notNull().default('byok'),
  status: connectionStatusEnum('status').notNull().default('pending'),

  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
  lastVerifiedAt: timestamp('last_verified_at', { withTimezone: true }),

  // Polish-3.5: per-account currency + tz + min-budget override. Populated
  // by the OAuth flow from /act_<id>?fields=currency,timezone_name; the
  // launch path reads these to convert USD → account currency / minor
  // units before calling Meta.
  accountCurrency: text('account_currency'),
  accountTimezone: text('account_timezone'),
  minDailyBudgetMinor: integer('min_daily_budget_minor'),
  // Page list captured at connect time. {id, name, accessToken, tasks[]}.
  // Used at launch to validate the picked page id + pull the page-scoped
  // token without re-hitting /me/accounts.
  pages:
    jsonb('pages').$type<
      Array<{ id: string; name: string; accessToken?: string; tasks?: string[] }>
    >(),

  // Soft delete.
  deletedAt: timestamp('deleted_at', { withTimezone: true }),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const telegramConnections = pgTable('telegram_connections', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),

  // Telegram chat id. Numeric in TG, stored as text for safety.
  tgChatId: text('tg_chat_id'),
  // One-time link code generated by web, redeemed by `/start <code>` in TG.
  linkCode: text('link_code').unique(),
  // Per-code expiry timestamp. Cleared on successful redemption. Distinct
  // from row-level created_at because we overwrite link_code on revisit.
  linkCodeGeneratedAt: timestamp('link_code_generated_at', { withTimezone: true }),
  linkedAt: timestamp('linked_at', { withTimezone: true }),

  status: connectionStatusEnum('status').notNull().default('pending'),

  metadata: jsonb('metadata').$type<{ tgUsername?: string }>(),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const aiProviderConnections = pgTable('ai_provider_connections', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),

  provider: aiProviderEnum('provider').notNull(),

  // Encrypted via pgcrypto + Supabase Vault key.
  apiKeyEncrypted: text('api_key_encrypted').notNull(),
  apiKeyVerifiedAt: timestamp('api_key_verified_at', { withTimezone: true }),

  status: connectionStatusEnum('status').notNull().default('pending'),
  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),

  // Soft delete.
  deletedAt: timestamp('deleted_at', { withTimezone: true }),

  isPrimary: boolean('is_primary').notNull().default(false),

  // Polish-4: per-provider tier (HeyGen free/pro/premium). Null for
  // providers without tiered APIs (Replicate, ElevenLabs). Drives the
  // premium-avatar filter — don't try a Premium avatar on a free key
  // (it 403s).
  tier: providerTierEnum('tier'),
  // Polish-4: last time we re-verified the connection (re-fetched
  // avatars / refreshed tier). Distinct from apiKeyVerifiedAt, which
  // is set on the initial connect and not bumped after.
  lastVerifiedAt: timestamp('last_verified_at', { withTimezone: true }),
  // Polish-4: flex bag for provider-specific cached state (e.g.
  // { heygen: { avatar_count, premium_avatar_ids } }).
  metadata: jsonb('metadata')
    .notNull()
    .default(sql`'{}'::jsonb`),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Phase 3a (migration 0008). BYOK credentials for non-UGC tools — Gemini
 * Vision (concept analysis), Claude (copy + prompt refinement), Kie.ai
 * (Sora 2 video gen). Distinct from `ai_provider_connections` which holds
 * Arcads/HeyGen/Creatify UGC video credentials. Per spec, Kie.ai lives
 * here even though it's a video provider.
 *
 * Same encryption + audit pattern as the other connection tables. Soft-
 * delete via `deleted_at`; one active row per (user, provider) enforced
 * by a partial unique index in the migration.
 */
export const toolConnections = pgTable('tool_connections', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),

  provider: toolProviderEnum('provider').notNull(),

  apiKeyEncrypted: text('api_key_encrypted').notNull(),
  apiKeyVerifiedAt: timestamp('api_key_verified_at', { withTimezone: true }),

  status: text('status').notNull().default('pending'),
  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),

  deletedAt: timestamp('deleted_at', { withTimezone: true }),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
