import type { LevelRequirement } from '@/types';

export const LEVEL_REQUIREMENTS: LevelRequirement[] = [
  { level: 2, followers: 200, tweets: 10 },
  { level: 3, followers: 500, tweetsOver5K: 1 },
  { level: 4, followers: 1000, tweetsOver5K: 5 },
  { level: 5, followers: 2500, revenue: 500 },
  { level: 6, followers: 5000, revenue: 1000, tweetsOver10K: 10 },
  { level: 7, followers: 10000, revenue: 5000 },
  { level: 8, followers: 25000, revenue: 10000 },
  { level: 9, followers: 50000, revenue: 25000 },
  { level: 10, followers: 100000, revenue: 100000 },
];

export const TWEET_TYPE_RARITY = {
  personal: 'common',
  engagement: 'common',
  'hot-take': 'rare',
  story: 'rare',
  sauce: 'epic',
  callout: 'epic',
  launch: 'epic',
  flex: 'rare',
} as const;

export const RARITY_COLORS = {
  common: { bg: 'bg-gray-600', text: 'text-gray-300', border: 'border-gray-500' },
  rare: { bg: 'bg-blue-600', text: 'text-blue-300', border: 'border-blue-400' },
  epic: { bg: 'bg-purple-600', text: 'text-purple-300', border: 'border-purple-400' },
  legendary: { bg: 'bg-yellow-600', text: 'text-yellow-300', border: 'border-yellow-400' },
} as const;

export const PERFORMANCE_THRESHOLDS = [
  { rating: 'legendary' as const, min: 100_000, emoji: '👑', label: 'Legendary' },
  { rating: 'viral' as const, min: 25_000, emoji: '⚡', label: 'Viral' },
  { rating: 'heat' as const, min: 5_000, emoji: '🔥', label: 'Heat' },
  { rating: 'mid' as const, min: 1_000, emoji: '😐', label: 'Mid' },
  { rating: 'flop' as const, min: 0, emoji: '💀', label: 'Flop' },
] as const;

export const XP_PER_ACTION = {
  postTweet: 10,
  views1K: 10,
  views5K: 25,
  views10K: 50,
  views25K: 100,
  views100K: 500,
  new100Followers: 30,
  firstRevenue: 200,
  per1KRevenue: 100,
  dailyGoalsComplete: 50,
  achievementUnlock: 100,
} as const;

export const STREAK_MULTIPLIERS = [
  { minDays: 30, multiplier: 3 },
  { minDays: 14, multiplier: 2 },
  { minDays: 7, multiplier: 1.5 },
  { minDays: 0, multiplier: 1 },
] as const;

export const EMPIRE_LEVEL_XP = [
  0, 100, 300, 600, 1000, 1500, 2500, 4000, 6000, 9000, 13000, 18000, 25000, 35000, 50000, 70000,
  100000, 150000, 250000, 500000,
];

export const BUILDING_EMOJIS: Record<number, string> = {
  1: '🛖',
  2: '🏠',
  3: '🏡',
  4: '🏢',
  5: '🏰',
  6: '🏯',
  7: '⛩️',
  8: '🏛️',
  9: '🗼',
  10: '👑',
};

export const HEALTH_CONFIG = {
  healthy: { emoji: '🟢', label: 'Healthy', color: 'text-green-400' },
  warning: { emoji: '🟡', label: 'Warning', color: 'text-yellow-400' },
  dying: { emoji: '🔴', label: 'Dying', color: 'text-red-400' },
  dead: { emoji: '💀', label: 'Dead', color: 'text-gray-400' },
} as const;

export const DEFAULT_ACCOUNTS = [
  {
    id: '1',
    handle: '@orsonwbs',
    niche: 'Affiliate/Info',
    color: '#F59E0B',
    level: 6,
    xp: 0,
    followers: 8500,
    revenue: 0,
    notes: 'Clicking.gg',
    tweetsPosted: 0,
    avgViews: 0,
    currentStreak: 0,
    lastPostedAt: null,
    createdAt: new Date().toISOString(),
    gridPosition: { row: 1, col: 2 },
  },
  {
    id: '2',
    handle: '@yllevan2',
    niche: 'Affiliate/Meta Bot',
    color: '#3B82F6',
    level: 1,
    xp: 0,
    followers: 541,
    revenue: 0,
    notes: 'Meta automation bot',
    tweetsPosted: 0,
    avgViews: 0,
    currentStreak: 0,
    lastPostedAt: null,
    createdAt: new Date().toISOString(),
    gridPosition: { row: 0, col: 1 },
  },
  {
    id: '3',
    handle: '@rhodesfbcs',
    niche: 'Gambling/Betting',
    color: '#EF4444',
    level: 1,
    xp: 0,
    followers: 0,
    revenue: 0,
    notes: 'Sports betting AI bot',
    tweetsPosted: 0,
    avgViews: 0,
    currentStreak: 0,
    lastPostedAt: null,
    createdAt: new Date().toISOString(),
    gridPosition: { row: 0, col: 3 },
  },
  {
    id: '4',
    handle: '@cantbuyhouse',
    niche: 'Clipping',
    color: '#22C55E',
    level: 2,
    xp: 0,
    followers: 0,
    revenue: 1000,
    notes: '$1K/mo promote.fun',
    tweetsPosted: 0,
    avgViews: 0,
    currentStreak: 0,
    lastPostedAt: null,
    createdAt: new Date().toISOString(),
    gridPosition: { row: 2, col: 1 },
  },
  {
    id: '5',
    handle: '@nolanmerc',
    niche: 'AI Launch System',
    color: '#A855F7',
    level: 1,
    xp: 0,
    followers: 460,
    revenue: 0,
    notes: 'AI system SaaS play',
    tweetsPosted: 0,
    avgViews: 0,
    currentStreak: 0,
    lastPostedAt: null,
    createdAt: new Date().toISOString(),
    gridPosition: { row: 2, col: 3 },
  },
  {
    id: '6',
    handle: '@zeyonws',
    niche: 'Gambling Rebrokering',
    color: '#EC4899',
    level: 1,
    xp: 0,
    followers: 0,
    revenue: 0,
    notes: 'Middleman offers',
    tweetsPosted: 0,
    avgViews: 0,
    currentStreak: 0,
    lastPostedAt: null,
    createdAt: new Date().toISOString(),
    gridPosition: { row: 1, col: 0 },
  },
  {
    id: '7',
    handle: '@terrificyashee',
    niche: 'YT SEO',
    color: '#06B6D4',
    level: 1,
    xp: 0,
    followers: 0,
    revenue: 0,
    notes: 'YT ranking method',
    tweetsPosted: 0,
    avgViews: 0,
    currentStreak: 0,
    lastPostedAt: null,
    createdAt: new Date().toISOString(),
    gridPosition: { row: 3, col: 2 },
  },
];
