-- Phase 7: beta access infrastructure.
--
-- Adds:
--   * invite_codes: single-use (or optional multi-use) codes that gate
--     signup. 30-day default expiry. Generated by admins.
--   * waitlist_entries: public-insert email capture for the queue
--     before invite. Admin approval generates a code + emails the user.
--   * user_settings.is_founding_member: auto-flagged for the first
--     FOUNDING_MEMBER_CAP (50) signups. Keep in sync with the
--     FOUNDING_MEMBER_CAP constant in @mbb/shared/safety.ts.
--   * users.signed_up_via_invite_code_id: which code this user
--     redeemed. Read off auth.users.raw_user_meta_data.invite_code_id
--     during the signup trigger.
--
-- Atomic signup: the auth.users INSERT trigger now also redeems the
-- code (increments use_count + sets the user-side fk + flips founding-
-- member when under cap). No separate server action — one SQL
-- transaction or it doesn't happen.
--
-- RLS note: we intentionally do NOT expose a public-select policy on
-- invite_codes. The spec's draft policy would let anyone enumerate
-- every valid code. Instead, signup validation runs server-side via
-- service-role (see apps/web/lib/invite-codes/validate.ts).
--
-- Idempotent.

-- =========================================================================
-- 1. invite_codes
-- =========================================================================
create table if not exists public.invite_codes (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  created_by uuid references public.users(id) on delete set null,
  is_multi_use boolean not null default false,
  max_uses integer not null default 1,
  use_count integer not null default 0,
  expires_at timestamptz not null default (now() + interval '30 days'),
  -- Free-form tags ("promo:twitter", "campaign:launch", etc).
  metadata jsonb not null default '{}'::jsonb,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_invite_codes_code on public.invite_codes(code);
create index if not exists idx_invite_codes_active
  on public.invite_codes(expires_at)
  where revoked_at is null;

alter table public.invite_codes enable row level security;

-- Admin-only access for the UI. The signup trigger runs as
-- SECURITY DEFINER and bypasses RLS to redeem.
drop policy if exists invite_codes_admin_all on public.invite_codes;
create policy invite_codes_admin_all on public.invite_codes
  for all using (public.is_admin()) with check (public.is_admin());

-- =========================================================================
-- 2. waitlist_entries
-- =========================================================================
create table if not exists public.waitlist_entries (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  name text,
  source text,
  message text,
  approved_at timestamptz,
  approved_by uuid references public.users(id) on delete set null,
  invite_code_id uuid references public.invite_codes(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_waitlist_entries_created
  on public.waitlist_entries(created_at desc);
create index if not exists idx_waitlist_entries_unapproved
  on public.waitlist_entries(created_at)
  where approved_at is null;

alter table public.waitlist_entries enable row level security;

drop policy if exists waitlist_entries_admin_all on public.waitlist_entries;
create policy waitlist_entries_admin_all on public.waitlist_entries
  for all using (public.is_admin()) with check (public.is_admin());

-- Unauthenticated visitors can submit themselves to the waitlist.
drop policy if exists waitlist_entries_insert_public on public.waitlist_entries;
create policy waitlist_entries_insert_public on public.waitlist_entries
  for insert with check (true);

-- =========================================================================
-- 3. user_settings + users extensions
-- =========================================================================
alter table public.user_settings
  add column if not exists is_founding_member boolean not null default false;

alter table public.users
  add column if not exists signed_up_via_invite_code_id uuid
  references public.invite_codes(id) on delete set null;

-- =========================================================================
-- 4. Founding-member eligibility function
-- =========================================================================
-- Keep in sync with FOUNDING_MEMBER_CAP in @mbb/shared/safety.ts.
create or replace function public.check_founding_member_eligibility()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  founding_member_cap constant integer := 50;
  current_count integer;
begin
  select count(*) into current_count
  from public.user_settings
  where is_founding_member = true;
  return current_count < founding_member_cap;
end;
$$;

-- =========================================================================
-- 5. Redefine the auth.users INSERT trigger to also:
--    a. Look up auth.users.raw_user_meta_data->>'invite_code_id'
--    b. Verify the code is still valid (not expired / not revoked /
--       not fully used) — bail if not
--    c. Increment use_count + link users.signed_up_via_invite_code_id
--    d. Call check_founding_member_eligibility() → set
--       user_settings.is_founding_member if eligible
-- Failures (invalid code) raise an exception — Supabase Auth surfaces
-- it back to the client.
-- =========================================================================
create or replace function public.tg_handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  invite_id_str text;
  invite_id uuid;
  code_row record;
  is_eligible boolean;
begin
  invite_id_str := new.raw_user_meta_data->>'invite_code_id';

  -- Phase 7: if an invite code was passed in metadata, validate +
  -- redeem it atomically with the user-row insert. If not present, we
  -- still create the row (admins seed users directly; existing test
  -- flows etc).
  if invite_id_str is not null and length(invite_id_str) > 0 then
    invite_id := invite_id_str::uuid;
    select * into code_row from public.invite_codes where id = invite_id for update;
    if code_row.id is null then
      raise exception 'invite_code_not_found';
    end if;
    if code_row.revoked_at is not null then
      raise exception 'invite_code_revoked';
    end if;
    if code_row.expires_at <= now() then
      raise exception 'invite_code_expired';
    end if;
    if code_row.use_count >= code_row.max_uses then
      raise exception 'invite_code_fully_used';
    end if;

    update public.invite_codes
       set use_count = use_count + 1
     where id = invite_id;
  end if;

  insert into public.users (id, email, full_name, signed_up_via_invite_code_id)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    invite_id
  )
  on conflict (id) do nothing;

  insert into public.user_settings (user_id) values (new.id) on conflict do nothing;

  -- Founding-member flag — runs after the user_settings row exists so
  -- the count query sees prior signups.
  select public.check_founding_member_eligibility() into is_eligible;
  if is_eligible then
    update public.user_settings
       set is_founding_member = true
     where user_id = new.id;
  end if;

  return new;
end;
$$;

-- Trigger itself unchanged; re-create defensively in case it was dropped.
drop trigger if exists handle_new_auth_user on auth.users;
create trigger handle_new_auth_user
after insert on auth.users
for each row execute function public.tg_handle_new_auth_user();
